### PR TITLE
Fix fnv1a hash output size detection on msvc arm64

### LINKED ISSUE #32: algorithm/hash is incompatible with MSVC arm64
https://github.com/ned14/quickcpplib/blob/9cdcd45d9036247dcade3d3ab1ff4adbe14b1927/include/quickcpplib/algorithm/hash.hpp#L51-L57

The arch detection list is missing `_M_ARM64`. However, I think keying on `SIZE_MAX` from `<cstdint>` should work without relying on compiler specifics.

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
Replace platform detection logic with a generic limit check.

Fixes #32

### CODE REVIEW

File: include/quickcpplib/algorithm/hash.hpp [hunk 1]
```diff
@@ -48,12 +49,12 @@ namespace algorithm
     {
       size_t operator()(T v) const
       {
-#if defined(__x86_64__) || defined(_M_X64) || defined(__aarch64__) || defined(__ia64__) || defined(_M_IA64) || defined(__ppc64__)
-        static constexpr size_t basis = 14695981039346656037ULL, prime = 1099511628211ULL;
-        static_assert(sizeof(size_t) == 8, "size_t is not 64 bit");
-#else
+#if SIZE_MAX == 0xffffffff
```
Comment (ned14) [inline include/quickcpplib/algorithm/hash.hpp:52]: The problem here that you are in no way guaranteed that `size_t` has any relation to the platform's native bit size. It could be seventeen bits on a 64 bit platform, for example. In case you're thinking that would never happen, alas I've worked on a 64 bit platform where size_t had a 40 bit range. And that made sense, because only 40 bits were addressable on that platform.

`UINTPTR_MAX` is a much better choice, but some platforms don't define it. `__SIZEOF_POINTER__` is another good choice, but also not always present. Can I suggest you ask if either of those two is defined, if they are, use them, otherwise fall back to the previous logic, except adding in MSVC's macro for ARM64?

May I also suggest moving said macro logic into config.hpp, define something like `QUICKCPPLIB_PLATFORM_NATIVE_BITLENGTH` or your name of choice, and then we concentrate all the special logic in one place. Also, make sure the user can predefine your choice of macro naming, and then the default setting logic gets skipped.

**Review by ned14 — CHANGES_REQUESTED** [review]

File: include/quickcpplib/algorithm/hash.hpp (hunk 1 above)
Comment (ned14) [reply include/quickcpplib/algorithm/hash.hpp:52]: Apologies for the late reply. So little free time recently. I think that the hash function works in `size_t` because `std::hash` returns a `size_t`, and that is incorrect: it should work in a known sized integer type and cast to `size_t` only on return.

I guess the preprocessor logic could be put into config.hpp and made more intelligent and probe various options before falling back onto raw architecture matching. I'll try to find some time to get this done later this week.

File: include/quickcpplib/algorithm/hash.hpp [hunk 2]
```diff
@@ -48,21 +49,21 @@ namespace algorithm
...
-        size_t ret = basis;
+        working_type ret = basis;
         for(size_t n = 0; n < sizeof(T); n++)
         {
-          ret ^= (size_t) _v[n];
+          ret ^= (working_type) _v[n];
           ret *= prime;
         }
-        return ret;
+        return size_t(ret);
```
Comment (BurningEnlightenment) [inline include/quickcpplib/algorithm/hash.hpp:66]: This will trigger GCC's semi useful `[-Wuseless-cast]` if `typeof(size_t) == typeof(working_type)` holds. I haven't found a good way to deal with these occurences 🙄 (suppressing them in place is so much clutter).

Comment (ned14) [reply include/quickcpplib/algorithm/hash.hpp:66]: Yup looks like `size_t` and `uint64_t` have identical type definition. I'll fix this shortly.
